name: Test C#

on:
  workflow_call:
    inputs:
      temp-version:
        description: 'A temporary build number to use for compiling the code'
        required: true
        type: string

permissions:
  packages: read

jobs:
  test-csharp:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: 'true'

      - name: Restore dependencies
        run: |
          nuget sources add -username Open-Systems-Pharmacology -password ${{ secrets.GITHUB_TOKEN }} -name OSP-GitHub-Packages -source "https://nuget.pkg.github.com/Open-Systems-Pharmacology/index.json"
          dotnet restore

      - name: Build
        run: dotnet build /p:Version=${{ inputs.temp-version }}

      - name: Test
        run: dotnet test -v normal --no-build  --logger:"html;LogFileName=../../../../testLog_Windows.html"